(async function () {
  const defaults = window.ATHLETE_DEFAULTS || {};
  const apiBase = window.RECRUITING_API_URL || '';
  const athleteId = document.documentElement.dataset.athleteId || 'cooper-fiddes';
  const sportNames={football:'Football',baseball:'Baseball',softball:'Softball',basketball:'Basketball',volleyball:'Volleyball',soccer:'Soccer',lacrosse:'Lacrosse',wrestling:'Wrestling','track-field':'Track & Field','cross-country':'Cross Country','swimming-diving':'Swimming & Diving',tennis:'Tennis',golf:'Golf','field-hockey':'Field Hockey','ice-hockey':'Ice Hockey',gymnastics:'Gymnastics',bowling:'Bowling',cheer:'Cheerleading',dance:'Dance','water-polo':'Water Polo',rowing:'Rowing / Crew',rugby:'Rugby','flag-football':'Flag Football',skiing:'Skiing',other:'Other'};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const normalize=s=>({...s,links:Array.isArray(s.links)?s.links:(Array.isArray(s.platforms)?s.platforms:[]),positions:Array.isArray(s.positions)?s.positions:[]});
  let a=defaults;
  try { const r=await fetch(apiBase?`${apiBase}/athletes/${athleteId}`:'./athlete.json',{cache:'no-store'}); if(r.ok)a={...defaults,...await r.json()}; } catch(_) {}
  document.querySelectorAll('[data-athlete]').forEach(el=>{const k=el.dataset.athlete;if(a[k]!=null)el.textContent=a[k]});
  document.querySelectorAll('[data-athlete-mail]').forEach(el=>{if(a.recruitingEmail)el.href=`mailto:${a.recruitingEmail}`});
  const root=document.documentElement;
  if(a.primaryColor)root.style.setProperty('--red',a.primaryColor); if(a.secondaryColor)root.style.setProperty('--dark',a.secondaryColor); if(a.accentColor)root.style.setProperty('--accent',a.accentColor);
  const hero=document.querySelector('#hero'); if(hero&&a.heroImageUrl){hero.style.backgroundImage=`linear-gradient(90deg,rgba(7,8,10,.96) 0%,rgba(7,8,10,.78) 42%,rgba(7,8,10,.15) 72%),linear-gradient(0deg,rgba(7,8,10,.65),rgba(7,8,10,0) 50%),url("${a.heroImageUrl}")`;hero.style.backgroundPosition=a.heroPosition||'center'}
  const head=document.querySelector('#profileHeadshot'), initials=document.querySelector('#profileInitials');
  if(head){if(a.headshotImageUrl){head.src=a.headshotImageUrl;head.hidden=false;if(initials)initials.hidden=true}else{head.hidden=true;if(initials){initials.textContent=`${(a.firstName||'A')[0]}${(a.lastName||'')[0]||''}`.toUpperCase();initials.hidden=false}}}
  const sports=(Array.isArray(a.sports)?a.sports:[]).map(normalize);
  const sub=document.querySelector('.sub'); if(sub)sub.textContent=`${a.school||''} · ${sports.length>1?'Multi-Sport Athlete':sports.length?`${sportNames[sports[0].sportId]||sports[0].sportName||'Student'} Athlete`:'Student-Athlete'}`;
  const chips=document.querySelector('.chips'); if(chips){chips.innerHTML='';sports.forEach(s=>{const d=document.createElement('div');d.className='chip';d.textContent=`${sportNames[s.sportId]||s.sportName||s.sportId} · ${(s.positions||[]).join(' / ')||'Athlete'}`;chips.appendChild(d)});[['height',`${a.height||''} · ${a.weight||''} lbs`],['gpa',`${a.gpa||''} GPA`]].forEach(([,t])=>{const d=document.createElement('div');d.className='chip';d.textContent=t;chips.appendChild(d)})}
  const nav=document.querySelector('nav .links'); if(nav){nav.innerHTML='';sports.forEach(s=>{const x=document.createElement('a');x.href=`#sport-${s.sportId}`;x.textContent=(sportNames[s.sportId]||s.sportName||s.sportId).toUpperCase();nav.appendChild(x)});nav.insertAdjacentHTML('beforeend','<a href="#academics">ACADEMICS</a><a href="#contact">CONTACT</a>')}
  const grid=document.querySelector('#sportsGrid'); if(grid&&sports.length){grid.innerHTML='';sports.forEach(s=>{const name=sportNames[s.sportId]||s.sportName||s.sportId,positions=(s.positions||[]).join(' · ')||'Athlete',links=(s.links||[]).filter(l=>l.url||l.platformName);const card=document.createElement('article');card.className='card';card.id=`sport-${s.sportId}`;card.innerHTML=`<div class="tag">${esc(name)}</div><h3>${esc(positions)}</h3><p>${esc(a.firstName||'This athlete')} competes in ${esc(name)} at ${esc(a.school||'their high school')}. View current recruiting, stats and video profiles below.</p><div class="platform-list">${links.map(l=>{const n=esc(l.platformName||'Profile'),domain=esc(l.domain||'');return `<a class="profile-card" href="${esc(l.url||'#')}" target="_blank" rel="noopener noreferrer"><span class="profile-logo">${esc((l.platformName||'?')[0].toUpperCase())}</span><span class="profile-copy"><strong>${n} Profile</strong><small>${domain||`View ${n}`}</small></span><span class="profile-arrow">↗</span></a>`}).join('')}</div><div class="coming">Recruiting film + verified stats can be added as the athlete profile develops</div>`;grid.appendChild(card)})}
  document.title=`${a.firstName||''} ${a.lastName||''} | Class of ${a.graduationYear||''} Student-Athlete`.trim();
})();
