(async function(){
 const defaults=window.ATHLETE_DEFAULTS||{},apiBase=window.RECRUITING_API_URL||'https://c90wgp9haf.execute-api.us-east-1.amazonaws.com/Prod',logoToken=(window.RUNTIME_CONFIG&&window.RUNTIME_CONFIG.logoDevPublicKey)||window.LOGO_DEV_TOKEN||'';const qs=new URLSearchParams(location.search);let athleteId=qs.get('athlete')||document.documentElement.dataset.athleteId||'cooper-fiddes';
 const host=location.hostname.replace(/^www\./,'');if(!/amplifyapp\.com$|localhost$|127\.0\.0\.1$/.test(host)){try{const r=await fetch(`${apiBase}/domains/resolve?domain=${encodeURIComponent(host)}`);if(r.ok){const x=await r.json();if(x.athleteId)athleteId=x.athleteId}}catch{}}
 const names={football:'Football',baseball:'Baseball',softball:'Softball',basketball:'Basketball',volleyball:'Volleyball',soccer:'Soccer',lacrosse:'Lacrosse',wrestling:'Wrestling','track-field':'Track & Field','cross-country':'Cross Country','swimming-diving':'Swimming & Diving',tennis:'Tennis',golf:'Golf','field-hockey':'Field Hockey','ice-hockey':'Ice Hockey',gymnastics:'Gymnastics',bowling:'Bowling',cheer:'Cheerleading',dance:'Dance','water-polo':'Water Polo',rowing:'Rowing / Crew',rugby:'Rugby','flag-football':'Flag Football',skiing:'Skiing',other:'Other'};
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const norm=s=>({...s,links:Array.isArray(s.links)?s.links:(Array.isArray(s.platforms)?s.platforms:[]),positions:Array.isArray(s.positions)?s.positions:[]});let a=defaults;try{const r=await fetch(`${apiBase}/athletes/${athleteId}`,{cache:'no-store'});if(r.ok)a={...defaults,...await r.json()}}catch{}
 document.querySelectorAll('[data-athlete]').forEach(el=>{const k=el.dataset.athlete;if(a[k]!=null)el.textContent=a[k]});document.querySelectorAll('[data-athlete-mail]').forEach(el=>{if(a.recruitingEmail)el.href=`mailto:${a.recruitingEmail}`});const root=document.documentElement;if(a.primaryColor)root.style.setProperty('--red',a.primaryColor);if(a.secondaryColor)root.style.setProperty('--dark',a.secondaryColor);if(a.accentColor)root.style.setProperty('--accent',a.accentColor);
 const hero=document.querySelector('#hero'),heroBg=document.querySelector('#heroBgImage');if(heroBg){if(a.heroImageUrl)heroBg.src=a.heroImageUrl;const hx=Number(a.heroPositionX??50),hy=Number(a.heroPositionY??50),hz=Number(a.heroZoom??1);heroBg.style.objectPosition=`${hx}% ${hy}%`;heroBg.style.transform=`scale(${hz})`}const head=document.querySelector('#profileHeadshot'),ini=document.querySelector('#profileInitials');if(head){if(a.headshotImageUrl){head.src=a.headshotImageUrl;head.hidden=false;if(ini)ini.hidden=true}else{head.hidden=true;if(ini){ini.textContent=`${(a.firstName||'A')[0]}${(a.lastName||'')[0]||''}`.toUpperCase();ini.hidden=false}}}
 const sports=(Array.isArray(a.sports)?a.sports:[]).map(norm),sub=document.querySelector('.sub');if(sub)sub.textContent=`${a.school||''} · ${sports.length>1?'Multi-Sport Athlete':sports.length?`${names[sports[0].sportId]||sports[0].sportName||'Student'} Athlete`:'Student-Athlete'}`;const chips=document.querySelector('.chips');if(chips){chips.innerHTML='';sports.forEach(s=>{const d=document.createElement('div');d.className='chip';d.textContent=`${names[s.sportId]||s.sportName||s.sportId} · ${(s.positions||[]).join(' / ')||'Athlete'}`;chips.appendChild(d)});[`${a.height||''} · ${a.weight||''} lbs`,`${a.gpa||''} GPA`].forEach(t=>{const d=document.createElement('div');d.className='chip';d.textContent=t;chips.appendChild(d)})}
 const nav=document.querySelector('nav .links');if(nav){nav.innerHTML='';sports.forEach(s=>{const x=document.createElement('a');x.href=`#sport-${s.sportId}`;x.textContent=(names[s.sportId]||s.sportName||s.sportId).toUpperCase();nav.appendChild(x)});nav.insertAdjacentHTML('beforeend','<a href="#academics">ACADEMICS</a><a href="#contact">CONTACT</a>')}
 const logo=l=>{const d=l.domain||(()=>{try{return new URL(l.url).hostname.replace(/^www\./,'')}catch{return''}})(),m=esc((l.platformName||'?')[0].toUpperCase());return logoToken&&d?`<img src="https://img.logo.dev/${esc(d)}?token=${encodeURIComponent(logoToken)}" alt="${esc(l.platformName||d)} logo" style="max-width:36px;max-height:36px" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><span class="logo-fallback" style="display:none">${m}</span>`:`<span class="logo-fallback">${m}</span>`};const grid=document.querySelector('#sportsGrid');if(grid&&sports.length){grid.innerHTML='';sports.forEach(s=>{const name=names[s.sportId]||s.sportName||s.sportId,links=(s.links||[]).filter(l=>l.url||l.platformName),card=document.createElement('article');card.className='card';card.id=`sport-${s.sportId}`;card.innerHTML=`<div class="tag">${esc(name)}</div><h3>${esc((s.positions||[]).join(' · ')||'Athlete')}</h3><p>${esc(a.firstName||'This athlete')} competes in ${esc(name)} at ${esc(a.school||'their high school')}.</p><div class="platform-list">${links.map(l=>`<a class="profile-card" href="${esc(l.url||'#')}" target="_blank" rel="noopener"><span class="profile-logo">${logo(l)}</span><span class="profile-copy"><strong>${esc(l.platformName||'Profile')} Profile</strong><small>${esc(l.domain||'')}</small></span><span class="profile-arrow">↗</span></a>`).join('')}</div>`;grid.appendChild(card)})}
 const videos=(Array.isArray(a.videos)?a.videos:[]).slice().sort((x,y)=>Number(!!y.featured)-Number(!!x.featured));if(videos.length){const section=document.createElement('section');section.id='videos';section.innerHTML='<h2 class="section-title">Video</h2><div class="grid" id="videoGrid"></div>';const sportsSection=grid?.closest('section');(sportsSection||document.querySelector('section'))?.insertAdjacentElement('afterend',section);const vg=section.querySelector('#videoGrid');videos.forEach(v=>{let embed='';try{const u=new URL(v.url);if(u.hostname.includes('youtube.com')&&u.searchParams.get('v'))embed=`https://www.youtube.com/embed/${u.searchParams.get('v')}`;else if(u.hostname==='youtu.be')embed=`https://www.youtube.com/embed/${u.pathname.slice(1)}`;else if(u.hostname.includes('vimeo.com'))embed=`https://player.vimeo.com/video/${u.pathname.split('/').filter(Boolean).pop()}`}catch{}const c=document.createElement('article');c.className='card';c.innerHTML=`<div class="tag">${esc(v.featured?'Featured Video':'Video')}</div><h3>${esc(v.title||'Athlete Video')}</h3>${embed?`<div style="aspect-ratio:16/9"><iframe src="${embed}" style="width:100%;height:100%;border:0;border-radius:10px" allowfullscreen></iframe></div>`:`<a class="profile-card" href="${esc(v.url||'#')}" target="_blank" rel="noopener"><span class="profile-logo">${logo({platformName:v.platformName||'Video',url:v.url,domain:v.domain||''})}</span><span class="profile-copy"><strong>Watch ${esc(v.platformName||'video')}</strong><small>${esc(v.url||'')}</small></span><span class="profile-arrow">↗</span></a>`}`;vg.appendChild(c)})}
 const fullName=`${a.firstName||''} ${a.lastName||''}`.trim();
 const academicCopy=document.querySelector('#academicCopy');if(academicCopy)academicCopy.textContent=`${a.firstName||'This athlete'} is a Class of ${a.graduationYear||''} student-athlete at ${a.school||'their high school'}. Academic information, honors and relevant coursework can be expanded as the high-school record develops.`;
 const contactCopy=document.querySelector('#contactCopy');if(contactCopy)contactCopy.textContent=`College coaches and recruiting staff can contact ${a.firstName||'the athlete'}’s family for additional film, schedules, references and recruiting information.`;
 document.querySelectorAll('[data-athlete-mail]').forEach(el=>{if(a.recruitingEmail){el.href=`mailto:${a.recruitingEmail}?subject=${encodeURIComponent(fullName+' Recruiting Inquiry')}`;if(el.dataset.athlete==='recruitingEmail')el.textContent=a.recruitingEmail}});
 const domainLabel=document.querySelector('#domainLabel');if(domainLabel)domainLabel.textContent=a.domain||host;
 const footer=document.querySelector('footer');if(footer)footer.textContent=`© 2026 ${fullName} · Student-Athlete Recruiting Profile`;
 const desc=document.querySelector('meta[name=description]');if(desc)desc.content=`${fullName} — Class of ${a.graduationYear||''} student-athlete at ${a.school||''}.`;
 document.title=`${fullName} | Class of ${a.graduationYear||''} Student-Athlete`.trim();
})();
