window.SPORTS_CATALOG = [
 {id:'football',name:'Football',fieldLabel:'Positions',options:['QB','RB','FB','WR','TE','OT','OG','C','DE','DT','NT','OLB','ILB','MLB','CB','S','K','P','LS','ATH']},
 {id:'baseball',name:'Baseball',fieldLabel:'Positions',options:['P','C','1B','2B','3B','SS','LF','CF','RF','OF','UTIL','DH']},
 {id:'softball',name:'Softball',fieldLabel:'Positions',options:['P','C','1B','2B','3B','SS','LF','CF','RF','OF','UTIL','DP']},
 {id:'basketball',name:'Basketball',fieldLabel:'Positions',options:['PG','SG','SF','PF','C','G','F','Wing']},
 {id:'volleyball',name:'Volleyball',fieldLabel:'Positions',options:['S','OH','OPP/RS','MB','L','DS']},
 {id:'soccer',name:'Soccer',fieldLabel:'Positions',options:['GK','CB','LB','RB','LWB','RWB','DM','CM','AM','LM','RM','LW','RW','ST','CF']},
 {id:'lacrosse',name:'Lacrosse',fieldLabel:'Positions',options:['A','M','D','G','LSM','FO','SSDM']},
 {id:'field-hockey',name:'Field Hockey',fieldLabel:'Positions',options:['GK','D','M','F']},
 {id:'ice-hockey',name:'Ice Hockey',fieldLabel:'Positions',options:['G','LD','RD','C','LW','RW','F','D']},
 {id:'wrestling',name:'Wrestling',fieldLabel:'Weight class',freeform:true},
 {id:'track-field',name:'Track & Field',fieldLabel:'Events',options:['60m','100m','200m','400m','800m','1600m','3200m','110m Hurdles','300m Hurdles','400m Hurdles','4x100','4x200','4x400','4x800','High Jump','Long Jump','Triple Jump','Pole Vault','Shot Put','Discus','Javelin','Pentathlon','Heptathlon','Decathlon']},
 {id:'cross-country',name:'Cross Country',fieldLabel:'Events / distance',options:['3K','5K','Other']},
 {id:'swimming-diving',name:'Swimming & Diving',fieldLabel:'Events',options:['50 Free','100 Free','200 Free','500 Free','100 Back','100 Breast','100 Fly','200 IM','200 Free Relay','200 Medley Relay','400 Free Relay','1m Diving','Other']},
 {id:'tennis',name:'Tennis',fieldLabel:'Events',options:['Singles','Doubles','Mixed Doubles']},
 {id:'golf',name:'Golf',fieldLabel:'Role / details',freeform:true},
 {id:'gymnastics',name:'Gymnastics',fieldLabel:'Events',options:['All-Around','Vault','Uneven Bars','Balance Beam','Floor','Pommel Horse','Still Rings','Parallel Bars','High Bar']},
 {id:'bowling',name:'Bowling',fieldLabel:'Role / details',freeform:true},
 {id:'cheer',name:'Cheerleading',fieldLabel:'Positions / skills',options:['Base','Back Spot','Flyer','Tumbler']},
 {id:'dance',name:'Dance',fieldLabel:'Styles / roles',freeform:true},
 {id:'water-polo',name:'Water Polo',fieldLabel:'Positions',options:['Goalkeeper','Center','Center Defender','Driver','Point','Wing']},
 {id:'rowing',name:'Rowing / Crew',fieldLabel:'Seat / role',options:['Coxswain','Stroke','Bow','Port','Starboard','Scull']},
 {id:'rugby',name:'Rugby',fieldLabel:'Positions',options:['Prop','Hooker','Lock','Flanker','No. 8','Scrum-half','Fly-half','Center','Wing','Fullback']},
 {id:'flag-football',name:'Flag Football',fieldLabel:'Positions',options:['QB','RB','WR','C','Rusher','DB','S','ATH']},
 {id:'skiing',name:'Skiing',fieldLabel:'Events',options:['Alpine','Nordic','Slalom','Giant Slalom','Downhill','Cross Country']},
 {id:'other',name:'Other',fieldLabel:'Positions / events / details',freeform:true}
];
